name: Test Project
on: push
jobs: 
  test:
    runs-on: ubuntu-latest
    outputs:
      outputTest: ${{ steps.setTest.outputs.test }}
    steps:
      - name : Get Code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm ci
      - name: Run test
        run: npm test
      - name: Setting the value
        id: setTest
        run: echo "test=world" >> $GITHUB_OUTPUT
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploying...
        run: |
         echo "Deploying the project"
         echo ${{ needs.test.outputs.outputTest }}